import { Category } from '@/types';
import { generateId } from '@/utils/uuid';

export const DEFAULT_CATEGORIES: Omit<Category, 'id' | 'created_at'>[] = [
  { name: 'Salary',         type: 'income',  color: '#4CAF50', icon: 'briefcase',        parent_id: null, is_system: 1 },
  { name: 'Freelance',      type: 'income',  color: '#66BB6A', icon: 'laptop',           parent_id: null, is_system: 1 },
  { name: 'Investment',     type: 'income',  color: '#81C784', icon: 'trending-up',      parent_id: null, is_system: 1 },
  { name: 'Other Income',   type: 'income',  color: '#A5D6A7', icon: 'plus-circle',      parent_id: null, is_system: 1 },
  { name: 'Food & Dining',  type: 'expense', color: '#EF5350', icon: 'food',             parent_id: null, is_system: 1 },
  { name: 'Transportation', type: 'expense', color: '#FF7043', icon: 'car',              parent_id: null, is_system: 1 },
  { name: 'Shopping',       type: 'expense', color: '#EC407A', icon: 'shopping',         parent_id: null, is_system: 1 },
  { name: 'Healthcare',     type: 'expense', color: '#AB47BC', icon: 'hospital-box',     parent_id: null, is_system: 1 },
  { name: 'Utilities',      type: 'expense', color: '#5C6BC0', icon: 'flash',            parent_id: null, is_system: 1 },
  { name: 'Rent / EMI',     type: 'expense', color: '#42A5F5', icon: 'home',             parent_id: null, is_system: 1 },
  { name: 'Entertainment',  type: 'expense', color: '#26C6DA', icon: 'television-play',  parent_id: null, is_system: 1 },
  { name: 'Education',      type: 'expense', color: '#26A69A', icon: 'school',           parent_id: null, is_system: 1 },
  { name: 'Travel',         type: 'expense', color: '#FFA726', icon: 'airplane',         parent_id: null, is_system: 1 },
  { name: 'Personal Care',  type: 'expense', color: '#FF8A65', icon: 'face-man',         parent_id: null, is_system: 1 },
  { name: 'Other Expense',  type: 'expense', color: '#BDBDBD', icon: 'dots-horizontal',  parent_id: null, is_system: 1 },
];

export const CATEGORY_KEYWORD_MAP: Record<string, string> = {
  swiggy: 'Food & Dining',
  zomato: 'Food & Dining',
  restaurant: 'Food & Dining',
  dining: 'Food & Dining',
  hotel: 'Food & Dining',
  cafe: 'Food & Dining',
  food: 'Food & Dining',
  uber: 'Transportation',
  ola: 'Transportation',
  petrol: 'Transportation',
  fuel: 'Transportation',
  metro: 'Transportation',
  irctc: 'Transportation',
  amazon: 'Shopping',
  flipkart: 'Shopping',
  myntra: 'Shopping',
  shopping: 'Shopping',
  medical: 'Healthcare',
  pharmacy: 'Healthcare',
  hospital: 'Healthcare',
  apollo: 'Healthcare',
  doctor: 'Healthcare',
  electricity: 'Utilities',
  water: 'Utilities',
  broadband: 'Utilities',
  emi: 'Rent / EMI',
  rent: 'Rent / EMI',
  loan: 'Rent / EMI',
  netflix: 'Entertainment',
  spotify: 'Entertainment',
  prime: 'Entertainment',
  hotstar: 'Entertainment',
  school: 'Education',
  college: 'Education',
  course: 'Education',
  salary: 'Salary',
  credit: 'Salary',
};
